name: Type-checking Svelte

on:
  push:
    branches: [main]
    paths:
      - 'src/**'

jobs:
  svelte-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.1
      - name: Check Svelte Code
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run check
